# Generated by Django 4.1.3 on 2022-12-01 23:32

from django.db import migrations, models
import django.db.models.deletion
import lessons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиция')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Синоним')),
                ('cover', models.ImageField(blank=True, default='', height_field='cower_h', max_length=300, upload_to=lessons.models.upload_to, verbose_name='Обложка', width_field='cower_w')),
                ('cower_w', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Ширина обложки')),
                ('cower_h', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Высота обложки')),
            ],
            options={
                'verbose_name': '_Школа',
                'verbose_name_plural': '_Школы',
                'db_table': 'schools',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Номер урока')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='Синоним')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, default='', height_field='cower_h', max_length=300, upload_to=lessons.models.upload_to, verbose_name='Обложка', width_field='cower_w')),
                ('cower_w', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Ширина обложки')),
                ('cower_h', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Высота обложки')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lessons', to='lessons.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons',
                'ordering': ('position',),
                'unique_together': {('position', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('1,1', 'Видео VK'), ('1,2', 'Видео YouTube'), ('1,3', 'Видео RuTube'), ('2,1', 'Аудио VK'), ('2,2', 'Аудио Yandex'), ('3,1', 'Текст')], max_length=10, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Текст')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Контент урока',
                'verbose_name_plural': 'Контент уроков',
                'db_table': 'lesson_content',
                'ordering': ('provider',),
                'unique_together': {('lesson', 'provider')},
            },
        ),
    ]
